blank_issues_enabled: false
contact_links:
  - name: No Github cuenta? no usará Github?
    url: https://50l.cc/gugu-qgroup
    about: Haga clic en el botón de la derecha para unirseQQComentarios del grupo
